language: node_js
node_js:
- '9.0'
os: [linux]
dist: trusty
sudo: true
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install rethinkdb
before_script:
    - rethinkdb --daemon
    - echo '{ "token": "my-super-secret-token" }' > auth.json
install:
  - yarn
script:
  - yarn build
